GOOGLE_CLIENT_ID: "202813200459-9sdkqv69qf1luv5ekt2lo0q45k7tgon2.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "kvkOXStNBg-bHPvlzXRuHzUW"

NAVER_CLIENT_ID: "0wvezfHMy7_ghHJ_hz2O"
NAVER_CLIENT_SECRET: "2TL97acenR"

FACEBOOK_CLIENT_ID: "2323839444535223"
FACEBOOK_CLIENT_SECRET: "b3320b454854204bf98365e8bcef2155"